package storage

import (
	"encoding/json"
	"fmt"
	"net"
	"sort"
	"strings"

	bolt "go.etcd.io/bbolt"
)

// CreateGeoEntry creates a new geofeed entry.
func (s *Store) CreateGeoEntry(entry *GeoEntry) error {
	if entry.ID == "" {
		entry.ID = GenerateID()
	}
	if err := validateGeoEntry(entry); err != nil {
		return err
	}
	err := s.db.Update(func(tx *bolt.Tx) error {
		b, err := tx.CreateBucketIfNotExists(BucketGeofeed)
		if err != nil {
			return err
		}
		data, err := json.Marshal(entry)
		if err != nil {
			return err
		}
		return b.Put([]byte(entry.ID), data)
	})
	if err == nil {
		recordChange(EntityTypeGeofeed, entry.ID, "", OpCreate, entry)
	}
	return err
}

// GetGeoEntry retrieves a geofeed entry by ID.
func (s *Store) GetGeoEntry(id string) (*GeoEntry, error) {
	var entry GeoEntry
	err := s.db.View(func(tx *bolt.Tx) error {
		b := tx.Bucket(BucketGeofeed)
		if b == nil {
			return nil
		}
		data := b.Get([]byte(id))
		if data == nil {
			return nil
		}
		return json.Unmarshal(data, &entry)
	})
	if err != nil {
		return nil, err
	}
	if entry.ID == "" {
		return nil, nil
	}
	return &entry, nil
}

// UpdateGeoEntry updates an existing geofeed entry.
func (s *Store) UpdateGeoEntry(entry *GeoEntry) error {
	if err := validateGeoEntry(entry); err != nil {
		return err
	}
	err := s.db.Update(func(tx *bolt.Tx) error {
		b := tx.Bucket(BucketGeofeed)
		if b == nil {
			return fmt.Errorf("geofeed bucket not found")
		}
		if b.Get([]byte(entry.ID)) == nil {
			return ErrNotFound
		}
		data, err := json.Marshal(entry)
		if err != nil {
			return err
		}
		return b.Put([]byte(entry.ID), data)
	})
	if err == nil {
		recordChange(EntityTypeGeofeed, entry.ID, "", OpUpdate, entry)
	}
	return err
}

// DeleteGeoEntry deletes a geofeed entry by ID.
func (s *Store) DeleteGeoEntry(id string) error {
	err := s.db.Update(func(tx *bolt.Tx) error {
		b := tx.Bucket(BucketGeofeed)
		if b == nil {
			return nil
		}
		return b.Delete([]byte(id))
	})
	if err == nil {
		recordChange(EntityTypeGeofeed, id, "", OpDelete, nil)
	}
	return err
}

// ListGeoEntries returns all geofeed entries.
func (s *Store) ListGeoEntries() ([]*GeoEntry, error) {
	var entries []*GeoEntry
	err := s.db.View(func(tx *bolt.Tx) error {
		b := tx.Bucket(BucketGeofeed)
		if b == nil {
			return nil
		}
		return b.ForEach(func(k, v []byte) error {
			var entry GeoEntry
			if err := json.Unmarshal(v, &entry); err != nil {
				return err
			}
			entries = append(entries, &entry)
			return nil
		})
	})
	return entries, err
}

// GetEnabledGeoEntries returns only enabled geofeed entries.
func (s *Store) GetEnabledGeoEntries() ([]*GeoEntry, error) {
	all, err := s.ListGeoEntries()
	if err != nil {
		return nil, err
	}
	var enabled []*GeoEntry
	for _, e := range all {
		if e.Enabled {
			enabled = append(enabled, e)
		}
	}
	return enabled, nil
}

// GenerateGeofeedCSV generates RFC 8805/9632 geofeed CSV content from enabled entries.
// Format: prefix,country_code,region,city,postal_code
func (s *Store) GenerateGeofeedCSV() (string, error) {
	entries, err := s.GetEnabledGeoEntries()
	if err != nil {
		return "", err
	}

	// Sort entries: IPv4 first, then IPv6, both by prefix
	sort.Slice(entries, func(i, j int) bool {
		iIsV6 := strings.Contains(entries[i].Prefix, ":")
		jIsV6 := strings.Contains(entries[j].Prefix, ":")
		if iIsV6 != jIsV6 {
			return !iIsV6 // IPv4 first
		}
		return entries[i].Prefix < entries[j].Prefix
	})

	var sb strings.Builder
	sb.WriteString("# RFC 8805 IP Geolocation Feed (RFC 9632 compliant)\n")
	sb.WriteString("# Generated by QTRL DNS Server\n")
	sb.WriteString("# prefix,country_code,region,city,postal_code\n")

	for _, e := range entries {
		sb.WriteString(fmt.Sprintf("%s,%s,%s,%s,%s\n",
			e.Prefix, e.Country, e.Region, e.City, e.PostalCode))
	}

	return sb.String(), nil
}

// validateGeoEntry validates a geofeed entry.
func validateGeoEntry(entry *GeoEntry) error {
	if entry.Prefix == "" {
		return fmt.Errorf("prefix is required")
	}
	// Validate CIDR notation
	_, _, err := net.ParseCIDR(entry.Prefix)
	if err != nil {
		return fmt.Errorf("invalid prefix CIDR: %v", err)
	}
	if entry.Country == "" {
		return fmt.Errorf("country code is required")
	}
	if len(entry.Country) != 2 {
		return fmt.Errorf("country must be a 2-letter ISO 3166-1 alpha-2 code")
	}
	return nil
}
